### ISSUE TITLE
getting `Unexpected token '('. Expected a property name.` 

### ISSUE THREAD

**Issue by focusteach** [quasarframework/app-extension-qzoom#1]
iOS version :11.1

**Comment by hawkeye64** [comment]
@focusteach Thanks for letting me know about this. This is the second time I have seen this error in a different App Extension. I think it is related to the quasar-mixin-colorize I am using. I think I will take a different approach and re-write quasar-mixin-colorize as an App Extsion. I think that will resolve things. It may take a while.

**Comment by hawkeye64** [comment]
Fixed in v1.0.0-alpha.4 - please let me know if you can test. If it works, please close this issue.

**Comment by hawkeye64** [comment]
@focusteach
