### ISSUE TITLE
Keep original aspect ratio of image when Zoomed

### ISSUE THREAD

**Issue by martinpare** [quasarframework/app-extension-qzoom#3]
Hi there,

Your app extension is awesome et VERY usefull for my app. 

It would be great to keep the original aspect ratio of the image when it is zoomed.

The image is clipped by the viewport available, so, we loose parts of the image if the available 
 viewport's aspect ratio is not the same as image's aspect ratio.

BTW: greate work!

**Comment by hawkeye64** [comment]
Thanks for commenting. :heart: I will look into the issue. Probably some small CSS change needed. If you figure it out before I do, let me know.

**Comment by martinpare** [comment]
Thanks for the feedback.

Will let you know if I find something.

Also, it would be very interesting if we could use a combination (ex: SHIFT and MOUSE WHEEL) to zoom at the position of the mouse pointer.

Thanks again.

**Comment by hawkeye64** [comment]
@martinpare Ah, well I am not sure if CSS would let you do that, but drawing into a canvas element would. Unfortunately, not going to be doing that (adding canvas element).
